// Generated by CoffeeScript 1.6.3
var $, assert, fs, util, writejson, xQuery;

util = require('util');

fs = require('fs');

xQuery = require('../lib/htmlparser-query');

$ = xQuery.$;

assert = require('assert');

writejson = function(path, obj) {
  var ss;
  ss = util.inspect(obj, {
    showHidden: true,
    depth: null
  });
  return fs.writeFile(path, ss, function(err) {
    if (err) {
      throw err;
    }
    return console.log('write fin!');
  });
};

fs.readFile('./seemh.html', {
  encoding: 'utf-8'
}, function(err, data) {
  var dd, gg, x;
  dd = xQuery.load(data);
  gg = function(slt) {
    return dd.find(slt);
  };
  writejson('./seemh.json', dd.elms);
  x = gg('#chapter-list-0');
  assert(x.size() === 3);
  x = gg('.chapter-list ul li a[title]');
  return assert(x.size() === 63);
});
